//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAdvices.Entity.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITAdvices.Entity.Common.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione.
        /// </summary>
        public static string All_Attenzione {
            get {
                return ResourceManager.GetString("All_Attenzione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data errata.
        /// </summary>
        public static string All_DataErrata {
            get {
                return ResourceManager.GetString("All_DataErrata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La data non è nel formato richiesto.
        /// </summary>
        public static string All_DataFormato {
            get {
                return ResourceManager.GetString("All_DataFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La data non può essere precedente al 1753.
        /// </summary>
        public static string All_DataInferiore1753 {
            get {
                return ResourceManager.GetString("All_DataInferiore1753", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data obbligatoria.
        /// </summary>
        public static string All_DataObbligatoria {
            get {
                return ResourceManager.GetString("All_DataObbligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dettaglio.
        /// </summary>
        public static string All_Dettaglio {
            get {
                return ResourceManager.GetString("All_Dettaglio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina.
        /// </summary>
        public static string All_Elimina {
            get {
                return ResourceManager.GetString("All_Elimina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire un indirizzo email valido.
        /// </summary>
        public static string All_EmailErrata {
            get {
                return ResourceManager.GetString("All_EmailErrata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La data non può essere successiva alla data odierna.
        /// </summary>
        public static string All_ErroreDataMaggioreNow {
            get {
                return ResourceManager.GetString("All_ErroreDataMaggioreNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La data non può essere precedente alla data odierna.
        /// </summary>
        public static string All_ErroreDataMinoreNow {
            get {
                return ResourceManager.GetString("All_ErroreDataMinoreNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore, riprovare più tardi.&lt;/br&gt;&lt;/br&gt;Se il problema persiste inviare un&apos;e-mail alla casella &lt;a href=&quot;PensioniOffLine@inps.it&quot;&gt;&lt;font size=&quot;4&quot;&gt;Portale_APE@inps.it&lt;/font&gt;&lt;/a&gt; descrivendo dettagliatamente il punto esatto in cui si è verificato l&apos;errore ed indicando la tua UserName..
        /// </summary>
        public static string All_GenericError {
            get {
                return ResourceManager.GetString("All_GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato non valido: ammesse solo cifre numeriche e la virgola come separatore decimale.
        /// </summary>
        public static string All_ImportoFormatoPunto {
            get {
                return ResourceManager.GetString("All_ImportoFormatoPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire il numero di telefono in formato numerico.
        /// </summary>
        public static string All_TelefonoErrato {
            get {
                return ResourceManager.GetString("All_TelefonoErrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anagrafica automatica non disponibile, procedere con l&apos;inserimento manuale..
        /// </summary>
        public static string Anagrafica_AnagraficaNonTrovata {
            get {
                return ResourceManager.GetString("Anagrafica_AnagraficaNonTrovata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effettuare la ricerca del codice fiscale.
        /// </summary>
        public static string Anagrafica_CodFiscaleRicercaMancante {
            get {
                return ResourceManager.GetString("Anagrafica_CodFiscaleRicercaMancante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il cognome immesso non è coerente con il codice fiscale.
        /// </summary>
        public static string Anagrafica_CognomeIncoerenteCF {
            get {
                return ResourceManager.GetString("Anagrafica_CognomeIncoerenteCF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comune rilascio documento obbligatorio.
        /// </summary>
        public static string Anagrafica_ComuneRilascioDocumentoObbligatorio {
            get {
                return ResourceManager.GetString("Anagrafica_ComuneRilascioDocumentoObbligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La data di nascita specificata non è coerente con il codice fiscale.
        /// </summary>
        public static string Anagrafica_DataNascitaIncoerenteConCodiceFiscale {
            get {
                return ResourceManager.GetString("Anagrafica_DataNascitaIncoerenteConCodiceFiscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La data di rilascio del documento di riconoscimento non può essere antecedente alla data di nascita del titolare.
        /// </summary>
        public static string Anagrafica_DataRilascioDocumentoErrata {
            get {
                return ResourceManager.GetString("Anagrafica_DataRilascioDocumentoErrata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La data di rilascio del documento di riconoscimento dev&apos;essere precedente alla data odierna.
        /// </summary>
        public static string Anagrafica_DataRilascioDocumentoMinorediDataOdierna {
            get {
                return ResourceManager.GetString("Anagrafica_DataRilascioDocumentoMinorediDataOdierna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data di rilascio del documento obbligatoria.
        /// </summary>
        public static string Anagrafica_DataRilascioDocumentoObbligatoria {
            get {
                return ResourceManager.GetString("Anagrafica_DataRilascioDocumentoObbligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ente rilascio documento obbligatorio.
        /// </summary>
        public static string Anagrafica_EnteRilascioDocumentoObbligatorio {
            get {
                return ResourceManager.GetString("Anagrafica_EnteRilascioDocumentoObbligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;ente di rilascio del documento di riconoscimento non è compatibile con la cittadinanza del titolare.
        /// </summary>
        public static string Anagrafica_EnteRilascioErratoPerCittadinanza {
            get {
                return ResourceManager.GetString("Anagrafica_EnteRilascioErratoPerCittadinanza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;ente di rilascio del documento di riconoscimento non è compatibile con lo stato di residenza del titolare.
        /// </summary>
        public static string Anagrafica_EnteRilascioErratoPerResidenza {
            get {
                return ResourceManager.GetString("Anagrafica_EnteRilascioErratoPerResidenza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il luogo di rilascio del documento di riconoscimento non è coerente con il tipo di documento selezionato.
        /// </summary>
        public static string Anagrafica_LuogoRilascioDocumentoErrato {
            get {
                return ResourceManager.GetString("Anagrafica_LuogoRilascioDocumentoErrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazione rilascio documento obbligatoria.
        /// </summary>
        public static string Anagrafica_NazioneRilascioDocumentoObbligatoria {
            get {
                return ResourceManager.GetString("Anagrafica_NazioneRilascioDocumentoObbligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il nome immesso non è coerente con il codice fiscale.
        /// </summary>
        public static string Anagrafica_NomeIncoerenteCF {
            get {
                return ResourceManager.GetString("Anagrafica_NomeIncoerenteCF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il numero del documento di riconoscimento deve contenere solo caratteri alfanumerici; non sono ammessi caratteri speciali.
        /// </summary>
        public static string Anagrafica_NumeroDocumentoErrato {
            get {
                return ResourceManager.GetString("Anagrafica_NumeroDocumentoErrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero documento obbligatorio.
        /// </summary>
        public static string Anagrafica_NumeroDocumentoObbligatorio {
            get {
                return ResourceManager.GetString("Anagrafica_NumeroDocumentoObbligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia rilascio documento obbligatoria.
        /// </summary>
        public static string Anagrafica_ProvinciaRilascioDocumentoObbligatoria {
            get {
                return ResourceManager.GetString("Anagrafica_ProvinciaRilascioDocumentoObbligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&apos; obbligatorio inserire almeno un recapito tra telefono, cellulare, indirizzo email o indirizzo PEC.
        /// </summary>
        public static string Anagrafica_RecapitoObbligatorio {
            get {
                return ResourceManager.GetString("Anagrafica_RecapitoObbligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&apos; obbligatorio inserire almeno un recapito tra indirizzo email e indirizzo PEC.
        /// </summary>
        public static string Anagrafica_RecapitoObbligatorioCitt {
            get {
                return ResourceManager.GetString("Anagrafica_RecapitoObbligatorioCitt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo documento obbligatorio.
        /// </summary>
        public static string Anagrafica_TipoDocumentoObbligatorio {
            get {
                return ResourceManager.GetString("Anagrafica_TipoDocumentoObbligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Art. 13 del d.lgs. 30 giugno 2003, n. 196, recante &quot;Codice in materia di protezione dei dati personali&quot;&lt;/b&gt;&lt;BR/&gt;
        ///Ai sensi della normativa sulla protezione dei dati personali la informiamo che i dati da lei conferiti volontariamente saranno trattati esclusivamente nell’ambito di tutte le attività strettamente funzionali alla concessione dell’anticipo pensionistico (cosiddetto APE) previsto e disciplinato dalla legge n. 232 del 2016 e dal DPCM .&lt;BR/&gt;&lt;BR/&gt;
        ///Titolari del trattamento sono il Ministero del la [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Certfica_InformativaContenuto {
            get {
                return ResourceManager.GetString("Certfica_InformativaContenuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informativa sul trattamento dei dati personali.
        /// </summary>
        public static string Certifica_Informativa {
            get {
                return ResourceManager.GetString("Certifica_Informativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la certificazione del diritto all’anticipo finanziario a garanzia pensionistica di cui all’articolo 1, comma 168, della legge 11 dicembre 2016, n. 232 e articolo 4 del D.P.C.M.  ..... .&lt;BR/&gt;
        ///La certificazione del diritto è effettuata sulla base degli elementi e delle informazioni presenti negli archivi dell&apos;INPS, al momento della certificazione.&lt;BR/&gt;
        ///A tal fine, dichiaro di aver preso visione dell&apos;estratto conto contributivo e di non aver riscontrato anomalie.
        /// </summary>
        public static string Certifica_RichiestaCertificazioneAPE {
            get {
                return ResourceManager.GetString("Certifica_RichiestaCertificazioneAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore di comunicazione con il servizio {0}: {1}.
        /// </summary>
        public static string CommunicationError {
            get {
                return ResourceManager.GetString("CommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessione duplicata!!!.
        /// </summary>
        public static string Courtesy_SessioneDuplicata {
            get {
                return ResourceManager.GetString("Courtesy_SessioneDuplicata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessione scaduta!!!&lt;/br&gt;Rientrare utilizzando la voce &apos;Menu Iniziale&apos;.
        /// </summary>
        public static string Courtesy_SessioneScaduta {
            get {
                return ResourceManager.GetString("Courtesy_SessioneScaduta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dati non validi.
        /// </summary>
        public static string DatiNonValidi {
            get {
                return ResourceManager.GetString("DatiNonValidi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminazione eseguita correttamente.
        /// </summary>
        public static string EliminazioneOK {
            get {
                return ResourceManager.GetString("EliminazioneOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun dato disponibile..
        /// </summary>
        public static string EmptyData {
            get {
                return ResourceManager.GetString("EmptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ha restituito il seguente errore: {1}.
        /// </summary>
        public static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, errore nel metodo {1}: {2}.
        /// </summary>
        public static string GenericException {
            get {
                return ResourceManager.GetString("GenericException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore infrastrutturale con il servizio {0}.
        /// </summary>
        public static string InfrastructureError {
            get {
                return ResourceManager.GetString("InfrastructureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore tecnico nel recupero delle sedi.
        /// </summary>
        public static string Invio_ErroreSede {
            get {
                return ResourceManager.GetString("Invio_ErroreSede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore tecnico nell&apos;invio della domanda. Si prega di riprovare più tardi.
        /// </summary>
        public static string Invio_ErroreTecnico {
            get {
                return ResourceManager.GetString("Invio_ErroreTecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Domanda di Certificazione APE n° {0} è stata inviata con successo..
        /// </summary>
        public static string Invio_Esito {
            get {
                return ResourceManager.GetString("Invio_Esito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&apos; obbligatorio selezionare la sede di destinazione della domanda.
        /// </summary>
        public static string Invio_SelezionaSedeObbligatorio {
            get {
                return ResourceManager.GetString("Invio_SelezionaSedeObbligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scelta della sede INPS.
        /// </summary>
        public static string Invio_TitoloSede {
            get {
                return ResourceManager.GetString("Invio_TitoloSede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nel consumo del servizio {0}: {1}.
        /// </summary>
        public static string InvokingError {
            get {
                return ResourceManager.GetString("InvokingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non sono presenti certificazioni.
        /// </summary>
        public static string ListaCertificazioniVuota {
            get {
                return ResourceManager.GetString("ListaCertificazioniVuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email non inserita.
        /// </summary>
        public static string Login_EmailNonInserita {
            get {
                return ResourceManager.GetString("Login_EmailNonInserita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore in fase di Login.
        /// </summary>
        public static string Login_Errore {
            get {
                return ResourceManager.GetString("Login_Errore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password non inserita.
        /// </summary>
        public static string Login_PasswordNonInserita {
            get {
                return ResourceManager.GetString("Login_PasswordNonInserita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username e/o password errate.
        /// </summary>
        public static string Login_UsernamePasswordErrate {
            get {
                return ResourceManager.GetString("Login_UsernamePasswordErrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utenza non riconosciuta dal sistema.
        /// </summary>
        public static string NessunaUtenza {
            get {
                return ResourceManager.GetString("NessunaUtenza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione, è stato eseguito un nuovo login.
        /// </summary>
        public static string NewLogin {
            get {
                return ResourceManager.GetString("NewLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntamento errato al servizio {0}.
        /// </summary>
        public static string NoEndpoint {
            get {
                return ResourceManager.GetString("NoEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to risposta nulla o vuota.
        /// </summary>
        public static string NoResponse {
            get {
                return ResourceManager.GetString("NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La procedura è momentaneamente in manutenzione.&lt;/br&gt;Si prega di riprovare più tardi.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ente obbligatorio.
        /// </summary>
        public static string Prodotto_EnteObbligatorio {
            get {
                return ResourceManager.GetString("Prodotto_EnteObbligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fondo obbligatorio.
        /// </summary>
        public static string Prodotto_FondoObbligatorio {
            get {
                return ResourceManager.GetString("Prodotto_FondoObbligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestione obbligatoria.
        /// </summary>
        public static string Prodotto_GestioneObbligatoria {
            get {
                return ResourceManager.GetString("Prodotto_GestioneObbligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sede di destinazione obbligatoria.
        /// </summary>
        public static string Prodotto_SedeObbligatoria {
            get {
                return ResourceManager.GetString("Prodotto_SedeObbligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipologia obbligatoria.
        /// </summary>
        public static string Prodotto_TipologiaObbligatoria {
            get {
                return ResourceManager.GetString("Prodotto_TipologiaObbligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice fiscale obbligatorio.
        /// </summary>
        public static string Ricerca_CodFiscaleObbligatorio {
            get {
                return ResourceManager.GetString("Ricerca_CodFiscaleObbligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvataggio eseguito correttamente.
        /// </summary>
        public static string SalvataggioOK {
            get {
                return ResourceManager.GetString("SalvataggioOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore di sicurezza nel consumo del servizio {0}.
        /// </summary>
        public static string SecurityError {
            get {
                return ResourceManager.GetString("SecurityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente non abilitato.
        /// </summary>
        public static string UtenteNonAbilitato {
            get {
                return ResourceManager.GetString("UtenteNonAbilitato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun numero domanda generato.
        /// </summary>
        public static string WebDom_NoDomus {
            get {
                return ResourceManager.GetString("WebDom_NoDomus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individuata vulnerabilità di tipo Cross-site scripting (XSS).
        /// </summary>
        public static string XSS {
            get {
                return ResourceManager.GetString("XSS", resourceCulture);
            }
        }
    }
}
