//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAdvices.Entity.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public System.DateTime Data { get; set; }
        public string Username { get; set; }
        public string Category { get; set; }
        public string Message { get; set; }
        public string SessionId { get; set; }
        public string SessionState { get; set; }
    }
}
