//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAdvices.Entity.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utente
    {
        public System.Guid Id { get; set; }
        public string Username { get; set; }
        public int IdRuolo { get; set; }
        public string Email { get; set; }
        public System.DateTime DataRegistrazione { get; set; }
    
        public virtual Ruolo Ruolo { get; set; }
    }
}
